---
title: "Exporatory analysis of the crop health survey data"
author: "Sith J"
date: "November 17, 2015"
output: html_document
---

```{r}
library(RCurl) # run this package for load the data form the website 
library(readr)
file <- getURL("https://docs.google.com/spreadsheets/d/1zB7gNdI7Nk7SuHuPWcjzaKnjuwkvL6sOVMo0zMfuV-c/pub?gid=558862364&single=true&output=csv") # load data from the google drive

data <- read_csv(file, na = c(" ", "NA", "na", "-")) # read data which is formated as the csv
```

```{r}
library(dplyr)
library(psych)
library(VIM)

# change the name of variables to small letter
names(data) <- tolower(names(data))

# remove some columns numnessary

data <-  data %>% select(-c(phase,identifier, fa, fn, fp,
                   lfm, ced, cedjul, hd, hdjul,
                   cvr, varcoded, fymcoded, mu, nplsqm)
                )

data <- data %>% transform(
                  fno = as.numeric(fno),
                  country = as.factor(country),
                  year = as.factor(year),
                  season = as.factor(season),
                  lat = as.numeric(lat),
                  long = as.numeric(long),
                  village = as.character(village),
                  pc = as.factor(pc),
                  cem = as.factor(cem),     
                  ast = as.factor(ast),       
                  ccd = as.numeric(ccd),
                  vartype = as.factor(vartype),
                  fym = as.character(fym),
                  n = as.numeric(n),
                  p = as.numeric(p) ,
                  k = as.numeric(k),
                  mf = as.numeric(mf),        
                  wcp = as.factor(wcp),      
                  iu = as.numeric(iu),     
                  hu = as.numeric(hu),      
                  fu = as.numeric(fu),      
                  cs  = as.factor(cs),      
                  ldg  =  as.numeric(ldg),  
                  yield = as.numeric(yield) ,
                  dscum = as.factor(dscum),   
                  wecum = as.factor(wecum),   
                  ntmax = as.numeric(ntmax), 
                  npmax = as.numeric(npmax),    
                  nltmax = as.numeric(nltmax),  
                  nlhmax = as.numeric(nltmax),  
                  waa = as.numeric(waa),      
                  wba = as.numeric(wba) ,   
                  dhx =  as.numeric(dhx),  
                  whx =  as.numeric(whx),     
                  ssx  = as.numeric(ssx),  
                  wma = as.numeric(wma), 
                  lfa = as.numeric(lfa),
                  lma = as.numeric(lma),   
                  rha  = as.numeric(rha) ,
                  thrx = as.numeric(thrx),    
                  pmx = as.numeric(pmx),    
                  defa  = as.numeric(defa),
                  bphx = as.numeric(bphx),   
                  wbpx = as.numeric(wbpx),    
                  awx  = as.numeric(awx), 
                  rbx =as.numeric(rbx),   
                  rbbx = as.numeric(rbbx),  
                  glhx  = as.numeric(glhx), 
                  stbx=as.numeric(stbx),    
                  hbx= as.numeric(hbx),
                  bbx = as.numeric(bbx),    
                  blba = as.numeric(blba),    
                  lba = as.numeric(lba),    
                  bsa = as.numeric(bsa),    
                  blsa = as.numeric(blsa),  
                  nbsa = as.numeric(nbsa),  
                  rsa  = as.numeric(rsa),   
                  lsa = as.numeric(lsa),    
                  shbx = as.numeric(shbx) ,  
                  shrx = as.numeric(shrx),    
                  srx= as.numeric(srx),    
                  fsmx = as.numeric(fsmx),   
                  nbx =  as.numeric(nbx),   
                  dpx = as.numeric(dpx),    
                  rtdx  = as.numeric(rtdx),  
                  rsdx  = as.numeric(rsdx),
                  gsdx  =as.numeric(gsdx),   
                  rtx = as.numeric(rtx)
) 

#======================================================================
#=================== corract the variable type ========================
#======================================================================

# Now data are in the right format and ready to further analysis, but there are some variables needed to code as the number not character
# Before proforming cluster analysis which is the further analysis, I need to code the character to number

##### recode the previous crop

#if previosu crop data are rice, they will be coded as 1, but others, not rice, they will be coded as 0.

data$pc <- ifelse(data$pc == "rice", 1, 0)
data$pc <- as.factor(data$pc)

##### recode the crop establisment mothods


#Crop establisment method
levels(data$cem)[levels(data$cem) == "trp"] <- 1
levels(data$cem)[levels(data$cem) == "TPR"] <- 1
levels(data$cem)[levels(data$cem) == "DSR"] <- 2
levels(data$cem)[levels(data$cem) == "dsr"] <- 2

##### fym



data$fym <- ifelse(data$fym == "no", 0, 
                   ifelse(data$fym == "0", 0, 1
                   )
)
data$fym <- as.factor(data$fym)

##### Vartype


data$vartype <- ifelse(data$vartype == "tv", 1,
                       ifelse(data$vartype == "mv", 2,
                              ifelse(data$vartype == "hyb", 3, NA
                              )
                       )
)
data$vartype <- as.factor(data$vartype)

##### Weed control practices

# wcp weed control management
levels(data$wcp)[levels(data$wcp) == "hand"] <- 1

levels(data$wcp)[levels(data$wcp) == "herb"] <- 2

levels(data$wcp)[levels(data$wcp) == "herb-hand"] <- 3


# Crop Status
levels(data$cs)[levels(data$cs) == "very poor"] <- 1

levels(data$cs)[levels(data$cs) == "poor"] <- 2

levels(data$cs)[levels(data$cs) == "average"] <- 3

levels(data$cs)[levels(data$cs) == "good"] <- 4

levels(data$cs)[levels(data$cs) == "very good"] <- 5

## end of corraction

```

I subset the data by country.

```{r}
idn <- data %>% filter(country == "IDN")

ind <- data %>% filter(country == "IND")

phi <- data %>% filter(country == "PHL")

tha <- data %>% filter(country == "THA")

vnm <- data %>% filter(country == "VNM")

```

## India data Dry season

```{r fig.height=3, fig.width=3}
# for the production situation and injuries data 
ind.ds <- ind %>% filter(season == "DS") %>% select(pc:rtx)

result <- data.frame(describe(ind.ds))

result$sym <- ifelse(result$skew <= -1 | result$skew >= 1,"No", "Yes")

result

varnames <- colnames(ind.ds)
p <- list()
for(i in 1:length(varnames)) {
  gdata <- ind.ds[,varnames[i]]
p[[i]] <-  histMiss(as.data.frame(gdata), xlab = paste(varnames[i]))
}
```

## India data Wet season

```{r fig.height=3, fig.width=3}
# for the production situation and injuries data 
ind.ws <- ind %>% filter(season == "WS") %>% select(pc:rtx)

result <- data.frame(describe(ind.ws))
result$sym <- ifelse(result$skew <= -1 | result$skew >= 1,"No", "Yes")
result

varnames <- colnames(ind.ws)
p <- list()
for(i in 1:length(varnames)) {
  gdata <- ind.ws[,varnames[i]]
p[[i]] <-  histMiss(as.data.frame(gdata), xlab = paste(varnames[i]))
}
```


## Indonesia data Wet season

```{r fig.height=3, fig.width=3}
# for the production situation and injuries data 
idn.ws <- idn %>% filter(season == "WS") %>% select(pc:rtx)

result <- data.frame(describe(idn.ws))
result$sym <- ifelse(result$skew <= -1 | result$skew >= 1,"No", "Yes")
result

varnames <- colnames(idn.ws)
p <- list()
for(i in 1:length(varnames)) {
  gdata <- idn.ws[,varnames[i]]
p[[i]] <-  histMiss(as.data.frame(gdata), xlab = paste(varnames[i]))
}
```

## Indonesia data Wet season

```{r fig.height=3, fig.width=3}
# for the production situation and injuries data 
idn.ds <- idn %>% filter(season == "DS") %>% select(pc:rtx)

result <- data.frame(describe(idn.ds))
result$sym <- ifelse(result$skew <= -1 | result$skew >= 1,"No", "Yes")
result

varnames <- colnames(idn.ds)
p <- list()
for(i in 1:length(varnames)) {
  gdata <- idn.ds[,varnames[i]]
p[[i]] <-  histMiss(as.data.frame(gdata), xlab = paste(varnames[i]))
}
```

## Phillipines data Dry season

```{r fig.height=3, fig.width=3}
# for the production situation and injuries data 
phi.ds <- phi %>% filter(season == "DS") %>% select(pc:rtx)

result <- data.frame(describe(phi.ds))
result$sym <- ifelse(result$skew <= -1 | result$skew >= 1,"No", "Yes")
result

varnames <- colnames(phi.ds)
p <- list()
for(i in 1:length(varnames)) {
  gdata <- phi.ds[,varnames[i]]
p[[i]] <-  histMiss(as.data.frame(gdata), xlab = paste(varnames[i]))
}
```

## Phillipines data Wet season

```{r fig.height=3, fig.width=3}
# for the production situation and injuries data 
phi.ws <- phi %>% filter(season == "WS") %>% select(pc:rtx)

result <- data.frame(describe(phi.ws))
result$sym <- ifelse(result$skew <= -1 | result$skew >= 1,"No", "Yes")
result

varnames <- colnames(phi.ws)
p <- list()
for(i in 1:length(varnames)) {
  gdata <- phi.ws[,varnames[i]]
p[[i]] <-  histMiss(as.data.frame(gdata), xlab = paste(varnames[i]))
}
```

## Thailand data Wet season

```{r fig.height=3, fig.width=3}
# for the production situation and injuries data 
tha.ws <- tha %>% filter(season == "WS") %>% select(pc:rtx)

result <- data.frame(describe(tha.ws))
result$sym <- ifelse(result$skew <= -1 | result$skew >= 1,"No", "Yes")
result

varnames <- colnames(tha.ws)
p <- list()
for(i in 1:length(varnames)) {
  gdata <- tha.ws[,varnames[i]]
p[[i]] <-  histMiss(as.data.frame(gdata), xlab = paste(varnames[i]))
}
```

## Vietnam data Dry season

```{r fig.height=3, fig.width=3}
# for the production situation and injuries data 
vnm.ds <- vnm %>% filter(season == "DS") %>% select(pc:rtx)

result <- data.frame(describe(vnm.ds))
result$sym <- ifelse(result$skew <= -1 | result$skew >= 1,"No", "Yes")
result

varnames <- colnames(vnm.ds)
p <- list()
for(i in 1:length(varnames)) {
  gdata <- vnm.ds[,varnames[i]]
p[[i]] <-  histMiss(as.data.frame(gdata), xlab = paste(varnames[i]))
}
```

## Vietnam data Wet season

```{r fig.height=3, fig.width=3}
# for the production situation and injuries data 
vnm.ws <- vnm %>% filter(season == "WS") %>% select(pc:rtx)

result <- data.frame(describe(vnm.ws))
result$sym <- ifelse(result$skew <= -1 | result$skew >= 1,"No", "Yes")
result

varnames <- colnames(vnm.ws)
p <- list()
for(i in 1:length(varnames)) {
  gdata <- vnm.ws[,varnames[i]]
p[[i]] <-  histMiss(as.data.frame(gdata), xlab = paste(varnames[i]))
}
```
